.PHONY: clean All

All:
	@echo "----------Building project:[ week_1_opdracht_2 -  ]----------"
	@cd "week_1_opdracht_2" && "$(MAKE)" -f  "week_1_opdracht_2.mk"
clean:
	@echo "----------Cleaning project:[ week_1_opdracht_2 -  ]----------"
	@cd "week_1_opdracht_2" && "$(MAKE)" -f  "week_1_opdracht_2.mk" clean
