.PHONY: clean All

All:
	@echo "----------Building project:[ week_3_opdracht_2v2 -  ]----------"
	@cd "week_3_opdracht_2v2" && "$(MAKE)" -f  "week_3_opdracht_2v2.mk"
clean:
	@echo "----------Cleaning project:[ week_3_opdracht_2v2 -  ]----------"
	@cd "week_3_opdracht_2v2" && "$(MAKE)" -f  "week_3_opdracht_2v2.mk" clean
